---
title: "2024: Decoding Spotify Trends"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(janitor)
```

```{r}
dataset_2024 <- read_csv("data/2024_data.csv") |>
                clean_names() |>
                select(-tidal_popularity)|>
  mutate(
    track = iconv(track, from = "UTF-8", to = "ASCII//TRANSLIT"),
    artist = iconv(artist, from = "UTF-8", to = "ASCII//TRANSLIT")
  ) |> 
  filter(artist!= "xSyborg")
```


Column {data-width=550}
-----------------------------------------------------------------------

### Comparing Spotify Streams to Amount of Tik Tok Likes

```{r}
dataset_2024 |> 
  drop_na(tik_tok_likes) |> 
  mutate(tik_tok_likes_log=log10(tik_tok_likes)) |> 
mutate(
    tiktok_category = case_when(
      tik_tok_likes_log <= log10(1e6) ~ "Low",       
      tik_tok_likes_log <= log10(1e8) ~ "Medium",    
      tik_tok_likes_log > log10(1e8) ~ "High"        
    ),
    tiktok_category = factor(tiktok_category, levels = c("Low", "Medium", "High")) 
  ) |> 
  ggplot(aes(x = tiktok_category, y = spotify_streams, fill = tiktok_category)) +
  geom_boxplot() +
  scale_fill_manual(
  values = c(
    "Low" = "pink",
    "Medium" = "#1DB954",
    "High" = "darkgreen"
  )
) +
  labs(
    title = "Comparing Spotify Streams to Amount of TikTok Likes",
    x = "TikTok Likes",
    y = "Spotify Streams",
   fill = "TikTok Likes Category"
  ) +
   theme_minimal() 

```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r}
 dataset_2024 |>
    drop_na(artist)|>
  group_by(artist) |>
  summarize(total_spotify_streams = sum(spotify_streams, na.rm = TRUE)) |> 
  arrange(desc(total_spotify_streams)) |> 
  top_n(10, total_spotify_streams) |> 
  ggplot(aes(x=total_spotify_streams, y=reorder(artist, total_spotify_streams))) +
  geom_bar(stat = "identity", fill = "#1DB954") + 
  labs(
    title = "Top 10 Artists Spotify Streams",
    x = "Total Spotify Streams",
    y = "Artist"
  ) +
  theme_minimal(base_size = 15) +
  theme(
    plot.title = element_text(face = "bold", size = 18, hjust = 0.5),
    plot.subtitle = element_text(size = 14, hjust = 0.5),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) 
```

### Chart C

```{r}
 dataset_2024 |>
    drop_na(artist)|>
  group_by(artist) |>
  summarize(total_tt = sum(tik_tok_views, na.rm = TRUE)) |> 
  arrange(desc(total_tt)) |> 
  top_n(10, total_tt) |> 
  ggplot(aes(x=total_tt, y=reorder(artist, total_tt))) +
  geom_bar(stat = "identity", fill = "#1DB954") + 
  labs(
    title = "Top 10 Artists TikTok Views",
    x = "Total TikTok Views",
    y = "Artist"
  ) +
   theme_minimal(base_size = 15) +
  theme(
    plot.title = element_text(face = "bold", size = 18, hjust = 0.5),
    plot.subtitle = element_text(size = 14, hjust = 0.5),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) 
```