---
title: "Decoding Spotify Music Trends"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

## Motivation

The initial motivation for the project was to expand the understanding of why songs and artists trend on music streaming platforms, such as Spotify. Quality of music is certainly subjective, however it is interesting to consider whether measurable qualities such as danceability, valence, or beats per minute are associated with popularity. As a step further, we were motivated to examine whether these relationships between measurable quantities and popularities remained consistent throughout the calendar year or rather ebbed and flowed as the seasons changed. 

We were also curious about the consistency and interaction between various streaming and social media platforms. With the rapid rise of the social media site tik tok and continued usage of platforms such as Youtube and SoundCloud, we looked to examine whether popularity on one site might correlate to another, or alternatively if the sites appealed to user bases with different music preferences. 

Overall, our project goal was to provide context for why songs and artists become and maintain popularity. We aimed to perform exploratory analysis on our original motivating questions, as well as any secondary questions that arose throughout the project. 

## Related Work

We found a few sources of inspiration for this project, the first being Spotify Wrapped. Each year, Spotify provides users with a summary of their most listened to songs, artists, genres, etc., giving insight into their preferences. While we each have different music preferences, we thought it interesting to consider whether some qualities of music were universally appealing. 

While beginning our research, we found other projects in this space that served as further inspiration, including a capstone project completed by students at Carnegie Mellon University titled “[Competitive Analysis of the Music Streaming Industry](https://amt-lab.org/blog/2019/9/a-competitive-analysis-of-the-music-streaming-industry)”. This project considered trends and the competitive aspects of the music streaming market, and included consideration of various streaming and social media platforms. This project was influential as we decided to include interaction between various streaming platforms as part of our analysis. 

## Initial Questions


## Data


## Exploratory Analysis


## Additional Analysis


## Discussion
