---
title: "spotify_data.github.io.git"
author: "Annie Gorman"
date: "2024-11-07"
output: github_document
---
## The group members (names and UNIs)
* Meredith Steinberg (ms6826)
* Laura Bulmer (leb2236)
* Anne Gorman (akg2197)
* Iris Hart (iah2124)
* Mia Isaacs (mbi2110)
* Carolyn Martinez Jorge (cm3936) 

## The tentative project title
2023 and 2024 Spotify Trends

## The motivation for this project
We would like to explore top songs and artists on Spotify in 2023 based on several predictors including danceability, energy, liveness, etc. as well as year released and listener trends. This will offer insight into the factors that contribute to songs’ and artists’ popularity. We are also interested in exploring the 2024 Spotify data that includes similar information to 2023 Spotify dataset (playlist counts, streams across Spotify and Deezer, track name, album name, artist, release date, etc.) but also includes information on the songs’ YouTube views/likes, TikTok posts/likes/views, all time rank, explicit track, etc. It would also be interesting to compare songs that are included in both 2023 and 2024 (e.g., could compare danceability with number of Tik Tok likes).

## The intended final products
* Written report
* Webpage
* Screencast
* Github repo

## The anticipated data sources
* Kaggle Most Streamed Spotify Songs 2023
https://www.kaggle.com/datasets/nelgiriyewithana/top-spotify-songs-2023/data 
* Kaggle Most Streamed Spotify Songs 2024
https://www.kaggle.com/datasets/nelgiriyewithana/most-streamed-spotify-songs-2024 

## The planned analyses / visualizations / coding challenges
* Comparing presence and rank of song across Spotify, Apple Music, Deezer, and Shazam
* Comparing number of playlists song is included in on Spotify, Deezer and Apple Music 
* Comparing the qualitative features of the different tracks such as danceability, valence, and beats per minute. 
* Looking at trends throughout the year and across years with the danceability and valence of music (considering more danceable songs in the summer and sadder songs in the fall.) 
* Anticipated challenge: same variables are not present across datasets, so there may be some trouble merging into one large and complete dataset. It may also be challenging to compare across years (2023 vs. 2024) as many of the variables are not consistent between these datasets. 

## The planned timeline
* November 11-15 Project review meeting w/ TA
* December 7: 
Written report giving detailed project description
Webpage overview of project, with short explanatory video (published online)
Brief assessment of your teammates contributions (as a short document)
